### ISSUE TITLE
iOS 12 support?

### ISSUE THREAD

**Issue by danielrbrowne** [aptabase/aptabase-swift#13]
I noted that the `Package.swift` specifies a minimum of iOS 13, but Xcode 15.x allows a user to select a Minimum Deployment Target all the way down to iOS 12.0 for a project.

Are there any technical reasons preventing the package file specifying iOS 12 as the minimum version? If so, would you be happy to make this change? (Or I am happy to raise a PR for that?).

**Comment by goenning** [comment]
Hey @danielrbrowne 

I didn’t expect someone to be still supporting iOS 12 😅

I just opted for some reasonable low versions, but it *should* work with 12 too. 

 I’d be happy to merge a PR. 👏

**Comment by danielrbrowne** [comment]
It's purely for historical reasons on a pet project of mine that I first released in 2010.

It's not an iOS version that I plan to support for any real length of time but as I migrate away from Firebase/Flurry I want to make a release that captures as many of my existing users as possible (before I embark on bigger changes like a migration to SwiftUI etc that will necessitate a bump to a much more recent iOS version 😅).

I'll raise a PR later today with the iOS and tvOS changes for the package file and let you handle the release versioning etc assuming your CI is happy.

**Comment by danielrbrowne** [comment]
Ah this is probably something that I will just have to accept, I just tried this locally and of course you're using concurrency which is iOS 13.0 and above. No worries, I've just checked and I don't think I'm really losing too many users by dropping iOS 12. I'll close this issue now.
