### ISSUE TITLE
visionOS compatibility?

### ISSUE THREAD

**Issue by Black-Fox-2022** [aptabase/aptabase-swift#17]
Maybe I am doing smth wrong, but i think you have no option for visionOS here, which is why it does not work

![Bildschirmfoto 2024-02-03 um 11 32 01](https://github.com/aptabase/aptabase-swift/assets/106263486/97debcc3-f32c-480e-93b5-408d2ea667e7)

**Comment by goenning** [comment]
Is it not compiling?

**Comment by Black-Fox-2022** [comment]
No, maybe these are just shadow errors and their is another issue somewhere else, but even after relaunching it does not change

**Comment by goenning** [comment]
can you share the errors? I'll try a sample vision app soon

**Comment by MadeiraAlexandre** [comment]
<img width="1544" alt="image" src="https://github.com/aptabase/aptabase-swift/assets/33880764/3209b4d2-65dd-407b-b17f-cdcad74e5309">
Here's a screenshot showing the compile errors when trying to build when Aptabase package is included in the visionOS project.

**Comment by goenning** [comment]
Any idea how to fix it? I’m happy to merge a PR.

**Comment by goenning** [comment]
import VisionKit maybe?

**Comment by Black-Fox-2022** [comment]
It's difficult to try for us... Maybe import UIKit / SwiftUI when not only iOS but also visionOS?

**Comment by goenning** [comment]
Done, can you try this branch before I merge it?
https://github.com/aptabase/aptabase-swift/tree/visionos

**Comment by Black-Fox-2022** [comment]
Gonna do that later today!

**Comment by MadeiraAlexandre** [comment]
Hi, I can confirm that the visionOS branch is working. 
<img width="1390" alt="image" src="https://github.com/aptabase/aptabase-swift/assets/33880764/4cd192e6-a115-4dc9-a719-c2741a4fded4">
<img width="1178" alt="image" src="https://github.com/aptabase/aptabase-swift/assets/33880764/ceafbd98-5e85-4f48-82d7-abef7bca478c">

**Comment by goenning** [comment]
Thanks @MadeiraAlexandre 
0.3.7 was just released with this change :)
