### ISSUE TITLE
Support for device model?

### ISSUE THREAD

**Issue by manucheri** [aptabase/aptabase-swift#20]
I'm wondering if there are any plans to support the device name/model? Currently OS versions are supported, but I think it can be useful info to also know which device model the app is running on.

I don't think it would be hard to add on the Swift client side (at least not for iOS/macOS platforms) and can help with a PR there if needed, but I guess this will need to be supported on the server as well - so want to check if there is interest in this functionality first.

**Comment by goenning** [comment]
Yes, I'd like to support device model too.

The Kotlin SDK already supports it ( https://github.com/aptabase/aptabase-kotlin/pull/3/files ) but the server is not using/storing that info yet. 

Do you want to create a PR for Swift? Eventually when the server supports, you'll get that without having to rebuild the app again.

The property is called `deviceModel`

**Comment by manucheri** [comment]
@goenning Took at stab at it here: https://github.com/aptabase/aptabase-swift/pull/21 let me know what you think.
