### ISSUE TITLE
All user data is shown as "Debug Data"

### ISSUE THREAD

**Issue by Black-Fox-2022** [aptabase/aptabase-swift#26]
Since I've created my new apps a few days ago all the user data is shown as Debug Data.
My two other apps are still running fine with a working seperation between Debug and Production data.
Issue appears since #24 fix

@bircni

**Comment by kunalzigma** [comment]
Yes,same for us as well. After updating to 0.3.10 , this same issue is happening. All user data only in debug for the latest app versions which have aptabase 0.3.10.

**Comment by bircni** [comment]
The current Solution is to Release another App Version with Apatabase 0.3.8
