### ISSUE TITLE
Closure in Aptabase.trackEvent

### ISSUE THREAD

**Issue by bircni** [aptabase/aptabase-swift#3]
Hi I am just getting an error from track Event
<img width="600" alt="Bildschirmfoto 2023-06-10 um 09 49 47" src="https://github.com/aptabase/aptabase-swift/assets/75789103/ec060221-0e36-44d9-a613-d125d27e5ebb">
<img width="734" alt="Bildschirmfoto 2023-06-10 um 09 50 12" src="https://github.com/aptabase/aptabase-swift/assets/75789103/ce79e7cc-b061-42dd-ad0a-76da7c3057e9">

**Comment by goenning** [comment]
Is it easy to reproduce? Any example of how to cause this exception?

**Comment by bircni** [comment]
Unfortunately not...
Cannot reproduce it again 🥲
An error was catched and I tried to log it via Aptabase

**Comment by goenning** [comment]
have you tried logging an error like this or something similar?

```swift
                do {
                    // something that throws an error
                } catch {
                    Aptabase.shared.trackEvent("catch_error", with: ["error": error])
                }
```

If so, you could try using `error.localizedDescription` instead because the dict with custom props only accepts strings and numbers.

But it shouldn't crash though, I'll have a look at why that happens

**Comment by goenning** [comment]
@bircni try updating to 0.1.0, I changed the `trackEvent` signature to be more explicit with what types it accepts: Strings, Int, Float, etc. Anything else should throw a compilation error instead of failing during runtime.
